from dotenv import load_dotenv
load_dotenv()

from starter_app import app, db
from starter_app.models import User, Food_Group, Ingredient

with app.app_context():
  db.drop_all()
  db.create_all()

  ian = User(username = 'Ian', email = 'ian@aa.io', password = "password")
  javier = User(username = 'Javier', email = 'javier@aa.io', password = "password")
  dean = User(username = 'Dean', email = 'dean@aa.io', password = "password")
  angela = User(username = 'Angela', email = 'angela@aa.io', password = "password")
  soonmi = User(username = 'Soon-Mi', email = 'soonmi@aa.io', password = "password")
  alissa = User(username = 'Alissa', email = 'alissa@aa.io', password = "password")
  demo_user = User(username = 'Demo-User', email = 'demo@aa.io', password = "password")

  fruit = Food_Group(name = 'Fruit') #        1
  veg = Food_Group(name = 'Vegetable') #      2
  dairy = Food_Group(name = 'Dairy') #        3
  protein = Food_Group(name = 'Protein') #    4 
  condiment = Food_Group(name = 'Condiment')# 5
  beverage = Food_Group(name = 'Beverage') #  6
  grain = Food_Group(name = 'Grains') #       7
  other = Food_Group(name = 'Other') #        8


  db.session.add(fruit)
  db.session.add(veg)
  db.session.add(dairy)
  db.session.add(protein)
  db.session.add(condiment)
  db.session.add(beverage)
  db.session.add(other)

  db.session.commit()

  milk = Ingredient(name = 'Milk', expires_in = 10, food_group_id = 3)
  eggs = Ingredient(name = 'Eggs', expires_in = 30, food_group_id = 3)
  strawberries = Ingredient(name = 'Strawberries', expires_in = 6, food_group_id = 1)
  broccoli = Ingredient(name = 'Broccoli', expires_in = 5, food_group_id = 2)
  chicken_raw = Ingredient(name = 'Chicken (raw)', expires_in = 2, food_group_id = 4)
  ketchup = Ingredient(name = 'Ketchup', expires_in = 180, food_group_id = 5)
  oj = Ingredient(name = 'Orange Juice', expires_in = 7, food_group_id = 6)
  anchovies = Ingredient(name = 'Anchovies', expires_in = 60, food_group_id = 7)
  caviar = Ingredient(name = 'Caviar', expires_in = 21, food_group_id = 7)

  almond_milk = Ingredient(name = 'Almond Milk', expires_in = 30, food_group_id = 3)
  soy_milk = Ingredient(name = 'Soy Milk', expires_in = 8, food_group_id = 3)
  rice_milk = Ingredient(name = 'Rice Milk', expires_in = 8, food_group_id = 3)
  coco_milk = Ingredient(name = 'Coconut Milk', expires_in = 8, food_group_id = 3)
  butter = Ingredient(name = 'Butter', expires_in = 14, food_group_id = 3)
  butter_milk = Ingredient(name = 'Buttermilk', expires_in = 12, food_group_id = 3)
  cond_milk = Ingredient(name = 'Condensed Milk', expires_in = 18, food_group_id = 3)
  cott_chz = Ingredient(name = 'Cottage Cheese', expires_in = 8, food_group_id = 3)
  ricotta = Ingredient(name = 'Ricotta Cheese', expires_in = 6, food_group_id = 3)
  whipn_cream = Ingredient(name = 'Whipping Cream', expires_in = 10, food_group_id = 3)
  hvy_cream = Ingredient(name = 'Heavy Cream', expires_in = 18, food_group_id = 3)
  cool_whip = Ingredient(name = 'Cool Whip', expires_in = 8, food_group_id = 3)
  halfNhalf = Ingredient(name = 'Half & Half', expires_in = 8, food_group_id = 3)
  cream_chz = Ingredient(name = 'Cream Cheese', expires_in = 24, food_group_id = 3)
  egg_nog = Ingredient(name = 'Egg Nog', expires_in = 6, food_group_id = 3)
  hard_cheese = Ingredient(name = 'Hard Cheese', expires_in = 90, food_group_id = 3)
  shredded_hard_cheese = Ingredient(name = 'Shredded Hard Cheese', expires_in = 45, food_group_id = 3)
  semi_hard_cheese = Ingredient(name = 'Semi-Hard Cheese', expires_in = 45, food_group_id = 3)
  margarine = Ingredient(name = 'Margarine', expires_in = 45, food_group_id = 3)
  pudding = Ingredient(name = 'Pudding', expires_in = 24, food_group_id = 3)
  brie = Ingredient(name = 'Brie', expires_in = 7, food_group_id = 3)
  mozz = Ingredient(name = 'Mozzarella', expires_in = 12, food_group_id = 3)
  feta = Ingredient(name = 'Feta Cheese', expires_in = 7, food_group_id = 3)
  monterey = Ingredient(name = 'Monterey Jack', expires_in = 12, food_group_id = 3)
  muenster = Ingredient(name = 'Muenster Cheese', expires_in = 12, food_group_id = 3)
  havarti = Ingredient(name = 'Havarti Cheese', expires_in = 12, food_group_id = 3)
  gorg = Ingredient(name = 'Gorgonzola Cheese', expires_in = 12, food_group_id = 3)
  sour_cream = Ingredient(name = 'Sour Cream', expires_in = 12, food_group_id = 3)
  drink_yog = Ingredient(name = 'Drinkable Yogurt', expires_in = 8, food_group_id = 3)
  greek_yog = Ingredient(name = 'Greek Yogurt', expires_in = 12, food_group_id = 3)
  yogurt = Ingredient(name = 'Yogurt', expires_in = 17, food_group_id = 3)
  yogurt_fru = Ingredient(name = 'Yogurt & Fruit', expires_in = 8, food_group_id = 3)

  db.session.add(almond_milk)
  db.session.add(soy_milk)
  db.session.add(rice_milk)
  db.session.add(coco_milk)
  db.session.add(butter)
  db.session.add(butter_milk)
  db.session.add(cond_milk)
  db.session.add(cott_chz)
  db.session.add(ricotta)
  db.session.add(whipn_cream)
  db.session.add(hvy_cream)
  db.session.add(cool_whip)
  db.session.add(halfNhalf)
  db.session.add(egg_nog)
  db.session.add(hard_cheese)
  db.session.add(shredded_hard_cheese)
  db.session.add(semi_hard_cheese)
  db.session.add(margarine)
  db.session.add(pudding)
  db.session.add(brie)
  db.session.add(mozz)
  db.session.add(feta)
  db.session.add(monterey)
  db.session.add(muenster)
  db.session.add(havarti)
  db.session.add(gorg)
  db.session.add(sour_cream)
  db.session.add(drink_yog)
  db.session.add(greek_yog)
  db.session.add(yogurt)
  db.session.add(yogurt_fru)

  apple = Ingredient(name = 'Apple', expires_in = 21, food_group_id = 1)
  apricot = Ingredient(name = 'Apricot', expires_in = 8, food_group_id = 1)
  avocado = Ingredient(name = 'Avocado', expires_in = 4, food_group_id = 1)
  banana =  Ingredient(name = 'Banana', expires_in = 4, food_group_id = 1)
  bluberry = Ingredient(name = 'Blueberry', expires_in = 3, food_group_id = 1)
  cantalope = Ingredient(name = 'Cantaloupe', expires_in = 6, food_group_id = 1)
  cherry = Ingredient(name = 'Cherry', expires_in = 3, food_group_id = 1)
  figs = Ingredient(name = 'Fig', expires_in = 6, food_group_id = 1)
  grapefruit = Ingredient(name = 'Grapefruit', expires_in = 18, food_group_id = 1)
  grapes = Ingredient(name = 'Grapes', expires_in = 7, food_group_id = 1)
  honeydew = Ingredient(name = 'Honeydew', expires_in = 12, food_group_id = 1)
  kiwi = Ingredient(name = 'Kiwi', expires_in = 14, food_group_id = 1)
  lemon = Ingredient(name = 'Lemon', expires_in = 20, food_group_id = 1)
  lime = Ingredient(name = 'Lime', expires_in = 21, food_group_id = 1)
  mango = Ingredient(name = 'Mango', expires_in = 7, food_group_id = 1)
  orange = Ingredient(name = 'Orange', expires_in = 18, food_group_id = 1)
  papaya = Ingredient(name = 'Papaya', expires_in = 8, food_group_id = 1)
  pear = Ingredient(name = 'Pear', expires_in = 9, food_group_id = 1)
  pineapple = Ingredient(name = 'Pineapple', expires_in = 5, food_group_id = 1)
  pomegranite = Ingredient(name = 'Pomegranate', expires_in = 21, food_group_id = 1)
  tomato = Ingredient(name = 'Tomato', expires_in = 7, food_group_id = 1)
  watermelon = Ingredient(name = 'Watermelon', expires_in = 8, food_group_id = 1)

  db.session.add(apple)
  db.session.add(apricot)
  db.session.add(avocado)
  db.session.add(banana)
  db.session.add(bluberry)
  db.session.add(cantalope)
  db.session.add(cherry)
  db.session.add(figs)
  db.session.add(grapefruit)
  db.session.add(grapes)
  db.session.add(honeydew)
  db.session.add(kiwi)
  db.session.add(lemon)
  db.session.add(lime)
  db.session.add(mango)
  db.session.add(orange)
  db.session.add(papaya)
  db.session.add(pear)
  db.session.add(pineapple)
  db.session.add(pomegranite)
  db.session.add(tomato)
  db.session.add(watermelon)

  bread = Ingredient(name = 'Bread', expires_in = 4, food_group_id = 7)
  bagel = Ingredient(name = 'Bagel', expires_in = 3, food_group_id = 7)
  biscuit = Ingredient(name = 'Biscuit Dough', expires_in = 12, food_group_id = 7)
  bread_crumb = Ingredient(name = 'Bread Crumbs', expires_in = 135, food_group_id = 7)
  crutons = Ingredient(name = 'Crutons', expires_in = 135, food_group_id = 7)
  cereal = Ingredient(name = 'Cereal', expires_in = 135, food_group_id = 7)
  grits = Ingredient(name = 'Grits', expires_in = 365, food_group_id = 7)
  pasta = Ingredient(name = 'Pasta', expires_in = 365, food_group_id = 7)
  fresh_pasta = Ingredient(name = 'Fresh Pasta', expires_in = 4, food_group_id = 7)
  oatmean = Ingredient(name = 'Oatmeal', expires_in = 400, food_group_id = 7)
  popcorn = Ingredient(name = 'Popcorn', expires_in = 10000000, food_group_id = 7)
  rice = Ingredient(name = 'Rice', expires_in = 100000000, food_group_id = 7)
  tortilla = Ingredient(name = 'Tortilla', expires_in = 25, food_group_id = 7)

  db.session.add(bread)
  db.session.add(bagel)
  db.session.add(biscuit)
  db.session.add(bread_crumb)
  db.session.add(crutons)
  db.session.add(cereal)
  db.session.add(grits)
  db.session.add(pasta)
  db.session.add(fresh_pasta)
  db.session.add(oatmean)
  db.session.add(popcorn)
  db.session.add(rice)
  db.session.add(tortilla)

  bacon = Ingredient(name = 'Bacon', expires_in = 12, food_group_id = 4)
  beans = Ingredient(name = 'Fresh Beans', expires_in = 8, food_group_id = 4)
  beef = Ingredient(name = 'Raw Beef', expires_in = 2, food_group_id = 4)
  beef_jerky = Ingredient(name = 'Beef', expires_in = 500, food_group_id = 4)
  cooked_chicken = Ingredient(name = 'Cooked Chicken', expires_in = 7, food_group_id = 4)
  chick_broth = Ingredient(name = 'Chicken Broth', expires_in = 5, food_group_id = 4)
  clams = Ingredient(name = 'Clams', expires_in = 7, food_group_id = 4)
  crab = Ingredient(name = 'Crab', expires_in = 2, food_group_id = 4)
  deli_meat = Ingredient(name = 'Fresh Deli Meat', expires_in = 6, food_group_id = 4)
  bologna = Ingredient(name = 'Bologna', expires_in = 12, food_group_id = 4)
  salami = Ingredient(name = 'Salami', expires_in = 15, food_group_id = 4)
  peperoni = Ingredient(name = 'Pepperoni', expires_in = 15, food_group_id = 4)
  fish = Ingredient(name = 'Fish', expires_in = 2, food_group_id = 4)
  cooked_fish = Ingredient(name = 'Cooked Fish', expires_in = 5, food_group_id = 4)
  smoked_fish = Ingredient(name = 'Smoked Fish', expires_in = 6, food_group_id = 4)
  sardines = Ingredient(name = 'Canned Sardine', expires_in = 500, food_group_id = 4)
  ham = Ingredient(name = 'Ham', expires_in = 12, food_group_id = 4)
  ground_beed = Ingredient(name = 'Ground Beef', expires_in = 2, food_group_id = 4)
  hamburger = Ingredient(name = 'Cooked Burger', expires_in = 5, food_group_id = 4)
  hotdog = Ingredient(name = 'Hot Dog', expires_in = 10, food_group_id = 4)
  mussel = Ingredient(name = 'Mussels', expires_in = 4, food_group_id = 4)
  oyster = Ingredient(name = 'Oysters', expires_in = 2, food_group_id = 4)
  pork = Ingredient(name = 'Raw Pork', expires_in = 2, food_group_id = 4)
  ground_pork = Ingredient(name = 'Ground Pork', expires_in = 2, food_group_id = 4)
  pork_saus = Ingredient(name = 'Pork Sausage', expires_in = 4, food_group_id = 4)
  cook_pork = Ingredient(name = 'Cooked Pork', expires_in = 7, food_group_id = 4)
  salmon = Ingredient(name = 'Salmon', expires_in = 2, food_group_id = 4)
  shrimp = Ingredient(name = 'Shrimp', expires_in = 2, food_group_id = 4)
  cooked_shrimp = Ingredient(name = 'Cooked Shrimp', expires_in = 3, food_group_id = 4)
  tofu = Ingredient(name = 'Tofu', expires_in = 4, food_group_id = 4)
  ra_turkey = Ingredient(name = 'Raw Turkey', expires_in = 2, food_group_id = 4)
  cooked_turkey = Ingredient(name = 'Cooked Turkey', expires_in = 7, food_group_id = 4)

  db.session.add(bacon)
  db.session.add(beans)
  db.session.add(beef)
  db.session.add(beef_jerky)
  db.session.add(cooked_chicken)
  db.session.add(chick_broth)
  db.session.add(clams)
  db.session.add(crab)
  db.session.add(deli_meat)
  db.session.add(bologna)
  db.session.add(salami)
  db.session.add(peperoni)
  db.session.add(fish)
  db.session.add(cooked_fish)
  db.session.add(smoked_fish)
  db.session.add(sardines)
  db.session.add(ham)
  db.session.add(ground_beed)
  db.session.add(hamburger)
  db.session.add(hotdog)
  db.session.add(mussel)
  db.session.add(oyster)
  db.session.add(pork)
  db.session.add(ground_pork)
  db.session.add(cook_pork)
  db.session.add(salmon)
  db.session.add(shrimp)
  db.session.add(cooked_shrimp)
  db.session.add(tofu)
  db.session.add(ra_turkey)
  db.session.add(cooked_turkey)

  artichoke = Ingredient(name = 'Artichoke', expires_in = 3, food_group_id = 2)
  asparagus = Ingredient(name = 'Asparagus', expires_in = 6, food_group_id = 2)
  brussel = Ingredient(name = 'Brussel Sprout', expires_in = 12, food_group_id = 2)
  cabbage = Ingredient(name = 'Cabbage', expires_in = 28, food_group_id = 2)
  carrot = Ingredient(name = 'Carrot', expires_in = 30, food_group_id = 2)
  cauli = Ingredient(name = 'Cauliflower', expires_in = 14, food_group_id = 2)
  celery = Ingredient(name = 'Celery', expires_in = 25, food_group_id = 2)
  corn = Ingredient(name = 'Corn', expires_in = 6, food_group_id = 2)
  cucumb = Ingredient(name = 'Cucumber', expires_in = 7, food_group_id = 2)
  eggplant = Ingredient(name = 'Eggplant', expires_in = 16, food_group_id = 2)
  garlic = Ingredient(name = 'Garlic', expires_in = 150, food_group_id = 2)
  green_bean = Ingredient(name = 'Green Bean', expires_in = 6, food_group_id = 2)
  kale = Ingredient(name = 'Kale', expires_in = 12, food_group_id = 2)
  lemongrass = Ingredient(name = 'Lemongrass', expires_in = 15, food_group_id = 2)
  iceburg = Ingredient(name = 'Iceburg Lettuce', expires_in = 8, food_group_id = 2)
  romaine = Ingredient(name = 'Romaine Lettuce', expires_in = 8, food_group_id = 2)
  leaf = Ingredient(name = 'Leaf Lettuce', expires_in = 6, food_group_id = 2)
  butterleaf = Ingredient(name = 'Butterleaf Lettuce', expires_in = 4, food_group_id = 2)
  loose_lettuce = Ingredient(name = 'Loose Lettuce', expires_in = 4, food_group_id = 2)
  mush = Ingredient(name = 'Mushroom', expires_in = 8, food_group_id = 2)
  onion = Ingredient(name = 'Onion', expires_in = 35, food_group_id = 2)
  parsnip = Ingredient(name = 'Parsnip', expires_in = 5, food_group_id = 2)
  bell_pep = Ingredient(name = 'Bell Pepper', expires_in = 14, food_group_id = 2)
  potato = Ingredient(name = 'Potato', expires_in = 90, food_group_id = 2)
  pickle = Ingredient(name = 'Pickles', expires_in = 365, food_group_id = 2)
  pumpkin = Ingredient(name = 'Pumpkin', expires_in = 90, food_group_id = 2)
  spinach = Ingredient(name = 'Spinach', expires_in = 6, food_group_id = 2)
  squash = Ingredient(name = 'Squash', expires_in = 50, food_group_id = 2)
  tomato = Ingredient(name = 'Tomatoes', expires_in = 14, food_group_id = 2)
  zucchini = Ingredient(name = 'Zucchini', expires_in = 6, food_group_id = 2)

  db.session.add(artichoke)
  db.session.add(asparagus)
  db.session.add(brussel)
  db.session.add(cabbage)
  db.session.add(carrot)
  db.session.add(cauli)
  db.session.add(celery)
  db.session.add(corn)
  db.session.add(cucumb)
  db.session.add(eggplant)
  db.session.add(garlic)
  db.session.add(green_bean)
  db.session.add(kale)
  db.session.add(lemongrass)
  db.session.add(iceburg)
  db.session.add(romaine)
  db.session.add(leaf)
  db.session.add(butterleaf)
  db.session.add(loose_lettuce)
  db.session.add(mush)
  db.session.add(onion)
  db.session.add(parsnip)
  db.session.add(bell_pep)
  db.session.add(potato)
  db.session.add(pickle)
  db.session.add(pumpkin)
  db.session.add(spinach)
  db.session.add(squash)
  db.session.add(tomato)
  db.session.add(zucchini)

  beer = Ingredient(name = 'Beer', expires_in = 210, food_group_id = 6)
  apple_j = Ingredient(name = 'Apple Juice', expires_in = 8, food_group_id = 6)
  grape_j = Ingredient(name = 'Grape Juice', expires_in = 8, food_group_id = 6)
  mango_j = Ingredient(name = 'Mango Juice', expires_in = 6, food_group_id = 6)
  grapefruit_j = Ingredient(name = 'Grapefruit Juice', expires_in = 6, food_group_id = 6)
  cranberry_j = Ingredient(name = 'Cranberry Juice', expires_in = 16, food_group_id = 6)
  soft_drink = Ingredient(name = 'Soft Drink', expires_in = 280, food_group_id = 6)

  db.session.add(beer)
  db.session.add(apple_j)
  db.session.add(grape_j)
  db.session.add(mango_j)
  db.session.add(grapefruit_j)
  db.session.add(cranberry_j)
  db.session.add(soft_drink)

  db.session.add(ian)
  db.session.add(javier)
  db.session.add(dean)
  db.session.add(angela)
  db.session.add(soonmi)
  db.session.add(alissa)
  db.session.add(demo_user)

  db.session.add(milk)
  db.session.add(eggs)
  db.session.add(strawberries)
  db.session.add(broccoli)
  db.session.add(chicken_raw)
  db.session.add(ketchup)
  db.session.add(oj)
  db.session.add(anchovies)
  db.session.add(caviar)

  db.session.commit()