"""empty message

Revision ID: 4fc587dbf88e
Revises: 55918bc961e0
Create Date: 2020-12-04 15:48:39.345135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fc587dbf88e'
down_revision = '55918bc961e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pic_url', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pic_url')
    # ### end Alembic commands ###
